import type { Metadata } from "next";
import { SFPro } from "@/utils/customFont";
import "../globals.css";
import { Navbar } from "@/components/Navbar/Navbar";
import { Footer } from "@/components/Footer/Footer";

export const metadata: Metadata = {
  title: "Chempion Social App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={SFPro.variable}>
      <head />
      <body className={SFPro.variable}>
        {children}
      </body>


    </html>
  );
}
