export const AllScoreGames = [
  [
    // MATCH 1 SCORE
    {
      opponent_1_score: 0,
      opponent_1_image: '/AllScores/user_1.png',
      opponent_1_nickname: 'vaness',
      opponent_1_energy: 47,
      opponent_1_birthLoc: 'Самарканд',
      opponent_1_age: 25,
      opponent_2_score: 0,
      opponent_2_image:'/AllScores/user_17.png', 
      opponent_2_nickname:'digi_digi',
      opponent_2_energy: 33,
      opponent_2_birthLoc: 'Самарканд',
      opponent_2_age: 25,
      sport_type: '/football.png',
      energy_icon: '/thunder.svg',
      location: 'Ташкент ул.Темур Малик. Стадион «Бунёдкор»',
      start_date:'12.06.2024  19:20',
      end_date:'12.06.2024  19:20',
      gallery: ['/AllScores/match_1_1.png', '/AllScores/match_1_2.png', '/AllScores/match_1_3.png',],
    },

    // MATCH 2 SCORE
    {
      opponent_1_score: 0,
      opponent_1_image: '/AllScores/user_1.png',
      opponent_1_nickname: 'vaness',
      opponent_1_energy: 47,
      opponent_1_birthLoc: 'Самарканд',
      opponent_1_age: 25,
      opponent_2_score: 0,
      opponent_2_image:'/AllScores/user_17.png', 
      opponent_2_nickname:'digi_digi',
      opponent_2_energy: 33,
      opponent_2_birthLoc: 'Самарканд',
      opponent_2_age: 25,
      sport_type: '/football.png',
      energy_icon: '/thunder.svg',
      location: 'Ташкент ул.Темур Малик. Стадион «Бунёдкор»',
      start_date:'12.06.2024  19:20',
      end_date:'12.06.2024  19:20',
      gallery: ['/AllScores/match_1_1.png', '/AllScores/match_1_2.png', '/AllScores/match_1_3.png',],
    },

    // MATCH 3 SCORE
    {
      opponent_1_score: 0,
      opponent_1_image: '/AllScores/user_1.png',
      opponent_1_nickname: 'vaness',
      opponent_1_energy: 47,
      opponent_1_birthLoc: 'Самарканд',
      opponent_1_age: 25,
      opponent_2_score: 0,
      opponent_2_image:'/AllScores/user_17.png', 
      opponent_2_nickname:'digi_digi',
      opponent_2_energy: 33,
      opponent_2_birthLoc: 'Самарканд',
      opponent_2_age: 25,
      sport_type: '/football.png',
      energy_icon: '/thunder.svg',
      location: 'Ташкент ул.Темур Малик. Стадион «Бунёдкор»',
      start_date:'12.06.2024  19:20',
      end_date:'12.06.2024  19:20',
    },

    // MATCH 4 SCORE
    {
      opponent_1_score: 0,
      opponent_1_image: '/AllScores/user_1.png',
      opponent_1_nickname: 'vaness',
      opponent_1_energy: 47,
      opponent_1_birthLoc: 'Самарканд',
      opponent_1_age: 25,
      opponent_2_score: 0,
      opponent_2_image:'/AllScores/user_17.png', 
      opponent_2_nickname:'digi_digi',
      opponent_2_energy: 33,
      opponent_2_birthLoc: 'Самарканд',
      opponent_2_age: 25,
      sport_type: '/football.png',
      energy_icon: '/thunder.svg',
      location: 'Ташкент ул.Темур Малик. Стадион «Бунёдкор»',
      start_date:'12.06.2024  19:20',
      end_date:'12.06.2024  19:20',
      gallery: ['/AllScores/match_1_1.png', '/AllScores/match_1_2.png', '/AllScores/match_1_3.png',],
    },
  ],

  [
    {
      opponent_1_score: 0,
      opponent_1_image: '/AllScores/user_1.png',
      opponent_1_nickname: 'vaness',
      opponent_1_energy: 47,
      opponent_1_birthLoc: 'Самарканд',
      opponent_1_age: 25,
      opponent_2_score: 0,
      opponent_2_image:'/AllScores/user_17.png', 
      opponent_2_nickname:'digi_digi',
      opponent_2_energy: 33,
      opponent_2_birthLoc: 'Самарканд',
      opponent_2_age: 25,
      sport_type: '/football.png',
      energy_icon: '/thunder.svg',
      location: 'Ташкент ул.Темур Малик. Стадион «Бунёдкор»',
      start_date:'12.06.2024  19:20',
      end_date:'12.06.2024  19:20',
    },

    {
      opponent_1_score: 0,
      opponent_1_image: '/AllScores/user_1.png',
      opponent_1_nickname: 'vaness',
      opponent_1_energy: 47,
      opponent_1_birthLoc: 'Самарканд',
      opponent_1_age: 25,
      opponent_2_score: 0,
      opponent_2_image:'/AllScores/user_17.png', 
      opponent_2_nickname:'digi_digi',
      opponent_2_energy: 33,
      opponent_2_birthLoc: 'Самарканд',
      opponent_2_age: 25,
      sport_type: '/football.png',
      energy_icon: '/thunder.svg',
      location: 'Ташкент ул.Темур Малик. Стадион «Бунёдкор»',
      start_date:'12.06.2024  19:20',
      end_date:'12.06.2024  19:20',
      gallery: ['/AllScores/match_1_1.png', '/AllScores/match_1_2.png', '/AllScores/match_1_3.png',],
    },

    {
      opponent_1_score: 0,
      opponent_1_image: '/AllScores/user_1.png',
      opponent_1_nickname: 'vaness',
      opponent_1_energy: 47,
      opponent_1_birthLoc: 'Самарканд',
      opponent_1_age: 25,
      opponent_2_score: 0,
      opponent_2_image:'/AllScores/user_17.png', 
      opponent_2_nickname:'digi_digi',
      opponent_2_energy: 33,
      opponent_2_birthLoc: 'Самарканд',
      opponent_2_age: 25,
      sport_type: '/football.png',
      energy_icon: '/thunder.svg',
      location: 'Ташкент ул.Темур Малик. Стадион «Бунёдкор»',
      start_date:'12.06.2024  19:20',
      end_date:'12.06.2024  19:20',
    },

    {
      opponent_1_score: 0,
      opponent_1_image: '/AllScores/user_1.png',
      opponent_1_nickname: 'vaness',
      opponent_1_energy: 47,
      opponent_1_birthLoc: 'Самарканд',
      opponent_1_age: 25,
      opponent_2_score: 0,
      opponent_2_image:'/AllScores/user_17.png', 
      opponent_2_nickname:'digi_digi',
      opponent_2_energy: 33,
      opponent_2_birthLoc: 'Самарканд',
      opponent_2_age: 25,
      sport_type: '/football.png',
      energy_icon: '/thunder.svg',
      location: 'Ташкент ул.Темур Малик. Стадион «Бунёдкор»',
      start_date:'12.06.2024  19:20',
      end_date:'12.06.2024  19:20',
      gallery: ['/AllScores/match_1_1.png', '/AllScores/match_1_2.png'],
    },
  ],
  
  [
    {
      opponent_1_score: 0,
      opponent_1_image: '/AllScores/user_1.png',
      opponent_1_nickname: 'vaness',
      opponent_1_energy: 47,
      opponent_1_birthLoc: 'Самарканд',
      opponent_1_age: 25,
      opponent_2_score: 0,
      opponent_2_image:'/AllScores/user_17.png', 
      opponent_2_nickname:'digi_digi',
      opponent_2_energy: 33,
      opponent_2_birthLoc: 'Самарканд',
      opponent_2_age: 25,
      sport_type: '/football.png',
      energy_icon: '/thunder.svg',
      location: 'Ташкент ул.Темур Малик. Стадион «Бунёдкор»',
      start_date:'12.06.2024  19:20',
      end_date:'12.06.2024  19:20',
      gallery: ['/AllScores/match_1_1.png', '/AllScores/match_1_2.png', '/AllScores/match_1_3.png',],
    },

    {
      opponent_1_score: 0,
      opponent_1_image: '/AllScores/user_1.png',
      opponent_1_nickname: 'vaness',
      opponent_1_energy: 47,
      opponent_1_birthLoc: 'Самарканд',
      opponent_1_age: 25,
      opponent_2_score: 0,
      opponent_2_image:'/AllScores/user_17.png', 
      opponent_2_nickname:'digi_digi',
      opponent_2_energy: 33,
      opponent_2_birthLoc: 'Самарканд',
      opponent_2_age: 25,
      sport_type: '/football.png',
      energy_icon: '/thunder.svg',
      location: 'Ташкент ул.Темур Малик. Стадион «Бунёдкор»',
      start_date:'12.06.2024  19:20',
      end_date:'12.06.2024  19:20',
    },

    {
      opponent_1_score: 0,
      opponent_1_image: '/AllScores/user_1.png',
      opponent_1_nickname: 'vaness',
      opponent_1_energy: 47,
      opponent_1_birthLoc: 'Самарканд',
      opponent_1_age: 25,
      opponent_2_score: 0,
      opponent_2_image:'/AllScores/user_17.png', 
      opponent_2_nickname:'digi_digi',
      opponent_2_energy: 33,
      opponent_2_birthLoc: 'Самарканд',
      opponent_2_age: 25,
      sport_type: '/football.png',
      energy_icon: '/thunder.svg',
      location: 'Ташкент ул.Темур Малик. Стадион «Бунёдкор»',
      start_date:'12.06.2024  19:20',
      end_date:'12.06.2024  19:20',
      gallery: ['/AllScores/match_1_1.png'],
    },

    {
      opponent_1_score: 0,
      opponent_1_image: '/AllScores/user_1.png',
      opponent_1_nickname: 'vaness',
      opponent_1_energy: 47,
      opponent_1_birthLoc: 'Самарканд',
      opponent_1_age: 25,
      opponent_2_score: 0,
      opponent_2_image:'/AllScores/user_17.png', 
      opponent_2_nickname:'digi_digi',
      opponent_2_energy: 33,
      opponent_2_birthLoc: 'Самарканд',
      opponent_2_age: 25,
      sport_type: '/football.png',
      energy_icon: '/thunder.svg',
      location: 'Ташкент ул.Темур Малик. Стадион «Бунёдкор»',
      start_date:'12.06.2024  19:20',
      end_date:'12.06.2024  19:20',
    },
  ],


]